/*
    Script to generate BRAND and PRICE tables
*/

CREATE TABLE IF NOT EXISTS BRAND
(
    BRAND_ID            BIGINT NOT NULL,
    BRAND_NAME          VARCHAR(200),
    PRIMARY KEY (BRAND_ID)
);

CREATE TABLE IF NOT EXISTS PRICES
(
    ID BIGINT NOT NULL,
    BRAND_ID            BIGINT NOT NULL,
    PRODUCT_ID          BIGINT NOT NULL,
    PRIORITY BIGINT NOT NULL,
    PRICE FLOAT(4) NOT NULL,
    PRICE_LIST BIGINT NOT NULL,
    START_DATE  DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    CURR CHAR(3) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT BRAND_ID_fk FOREIGN KEY (BRAND_ID) REFERENCES BRAND(BRAND_ID)
);
